### ISSUE TITLE
Need upgrade to Laravel 11

### ISSUE THREAD

**Issue by CeloGomesBR** [netflie/laravel-notification-whatsapp#23]
I can´t upgrade project to Laravel 11 because this package causing conflict.

netflie/laravel-notification-whatsapp 1.2.0 requires illuminate/support ~8.0 || ~9.0 || ~10.0

**Comment by fabianm1705** [comment]
no news on this problem?

**Comment by aalbarca** [comment]
Hi, Fixed in 1.3.0 version.

**Comment by fabianm1705** [comment]
Thanks!
