### ISSUE TITLE
using ->route() not working

### ISSUE THREAD

**Issue by devhereco** [netflie/laravel-notification-whatsapp#30]
Hi there, i have tried a few things with ->route but does not seem to be working with the whatsapp notification, and no errors are thrown  and queue dispatch does not get fired 

I tried
       Notification::route(WhatsAppChannel::class, 971555555555)
           ->notify(new VerifyPhoneNotification(1234));
           
and
       Notification::route('whatsapp, 971555555555)
           ->notify(new VerifyPhoneNotification(1234));
           
any idea

**Comment by meyer59** [comment]
Hey 
Did you find any solution to that ? i got the same issue, number parameters are not in the notifable
