### ISSUE TITLE
not compatible with laravel 10

### ISSUE THREAD

**Issue by maverik23** [netflie/laravel-notification-whatsapp#5]
It seems that it is not compatible with version 10+ of illuminate/notifications, could you change the required version to version 10+ to be able to use it with Laravel 10+?
or if there is any other way please let me know

`Problem 1
    - netflie/laravel-notification-whatsapp[v0.1.0, v1.0.0] require illuminate/notifications ~8.0 || ~9.0 -> found illuminate/notifications[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires netflie/laravel-notification-whatsapp * -> satisfiable by netflie/laravel-notification-whatsapp[v0.1.0, v1.0.0].
`

**Comment by albertobenavides** [comment]
I am also interested in this :)

**Comment by aalbarca** [comment]
Hi,

Can you help me? Try to install the branch dev-laravel-10 and let me know if is working -> https://packagist.org/packages/netflie/laravel-notification-whatsapp#dev-laravel-10

Thanks.

**Comment by maverik23** [comment]
> Hi,
> 
> Can you help me? Try to install the branch dev-laravel-10 and let me know if is working -> https://packagist.org/packages/netflie/laravel-notification-whatsapp#dev-laravel-10
> 
> Thanks.

Thanks man, this works fine.

**Comment by aalbarca** [comment]
Thanks @maverik23 

@albertobenavides can you confirm is also working for you? Thanks.

**Comment by albertobenavides** [comment]
@aalbarca, yes, thank you :)
